### ISSUE TITLE
Comically large spoon cant be bought at store.

### ISSUE THREAD

**Issue by SLY999-dev** [ZigzagAwaka/PremiumScraps#2]
Searching comically or the whole thing (comically large spoon) only brings up the company building. Any workaround or anything to fix this?
Anything is appreciated thanks.

**Comment by ZigzagAwaka** [comment]
Hi, first of all thanks for playing the mod and posting the issue !

However, this is not an issue at all lmao, this mod is supposed to add scrap items as collectable that you can find in dungeons.
Comically Large Spoon is a weapon scrap but that doesn't mean it can be bought in the shop, instead you can find it when exploring the dungeon

Also, if you think the Spoon is a little too hard to find (or any other item btw), you can increase the spawn chance in the config file

Have a great day !
